### PR TITLE
Switch to com.github.mwiede:jsch

### LINKED ISSUE #23: Switch to com.github.mwiede:jsch
... for reasons named in https://www.matez.de/index.php/2020/06/22/the-future-of-jsch-without-ssh-rsa/

### PR DESCRIPTION
**Pull request by jamesnetherton**
Fixes #23

### CODE REVIEW

**Comment by jamesnetherton** [comment]
Assuming this gets merged - any chance of getting a new release so that I can fix up the Camel Quarkus side?

**Review by gastaldi — APPROVED** [review]
LGTM

**Comment by gastaldi** [comment]
@all-contributors add @jamesnetherton for code and maintenance

**Comment by gastaldi** [comment]
@jamesnetherton 2.0.0 is now out, enjoy!

**Pull request merged**
